---

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    resource_to_telemetry_conversion: 
      enabled: true

receivers:
  prometheustextfile:
    directories: 
      - /Users/mburt/workspace/repos/github.com/opentelemetry-collector-contrib/receiver/prometheustextfilereceiver/.idea/

service:
  pipelines:
    metrics/local:
      receivers: [prometheustextfile]
      exporters: [prometheus]

